### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lrutjens** [MateuSai/Godot-Roguelike-Tutorial#6]
Whats the licensing on the code? Do you mind if i reuse it (mainly the dungeon generator) for my game?

**Comment by MateuSai** [comment]
Hey, sorry for the late reply. You can use the code however you like, the only conditions are that you not try to sell it without making modifications.

Credit is not mandatory, but appreciated, especially if you used a big part of the code.

Show me what you made with it. This is not a condition, but I would really like to see what you make with the project as base :)

**Comment by lrutjens** [comment]
I did end up making my own dungeon generator (as you can see it still needs a bit of work though), but I was making a dungeon crawler. You tutorial was a big inspiration for it 

<img width="343" alt="image" src="https://github.com/MateuSai/Godot-Roguelike-Tutorial/assets/93109413/2a5f60c4-a5a3-4786-b6b6-bdb1e02ca267">

**Comment by MateuSai** [comment]
It looks very good!
